alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- cluster_name: app-fb765a26-6c34-413d-b847-6882a173ff88
  db_name: dev-db-804350
  db_user: dev-db-804350
  engine: PG
  name: dev-db-804350
  production: true
  version: "17"
- cluster_name: dbaas-db-3754887
  db_name: sippdb
  db_user: sippadmin
  engine: MYSQL
  name: dbaas-db-3754887
  production: true
  version: "8.4"
envs:
- key: PRIVATE
  scope: RUN_TIME
  type: SECRET
  value: EV[1:Zq1DVDlVDeU0R83y8If/Qco02M8i8MCG:U9v6jZD385FanxOkFqA9uLpF939PDnIq1KXd076FMBMUq6w=]
- key: PUBLIC
  scope: RUN_TIME
  value: ${sipp.PUBLIC_URL}
- key: DATABASE_URL
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:YI8ytbJa/ws8Fwdi9+lt/Sm5z8NX0fqZ:cR4ZQ9cRG3zM585fwvXXKUQ+6r9eDTgsiWVOkXou2WoIohQtgqYDtbnfmobY8OGt]
- key: DATABASE_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${dbaas-db-3754887.HOSTNAME}
- key: DATABASE_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${dbaas-db-3754887.PORT}
- key: DATABASE_USER
  scope: RUN_AND_BUILD_TIME
  value: ${dbaas-db-3754887.USERNAME}
- key: DATABASE_PW
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:0Bl3EZtkmV/Num1AJlv9uvnq6+Z+1jA5:aGuzu+s7fse2bnOjGMaFvozOVQti4A3uqFpMxXjJrde8mHFJgyQJBOVzx5k=]
- key: DATABASE_CERT
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:eTrxFyKFlSQkRRLTIYZ/7N0WWQmlOtSx:OcgjLN5uxuCCDuBCABvaQ/WA9zQMKJUJmVPpNX4TYNA0c9qfju8M7BrNag==]
- key: DATABASE
  scope: RUN_AND_BUILD_TIME
  value: ${dbaas-db-3754887.DATABASE}
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: sipp
    match:
      authority:
        exact: ""
      path:
        prefix: /
  - component:
      name: sipp-sipp-app
    match:
      authority:
        exact: ""
      path:
        prefix: /sipp-sipp-app
name: sipp-app
region: sgp
services:
- environment_slug: php
  envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:bZ+LZzc57lPBdOZy+b+4vnZfOWSJD3YY:3QDXWwd6HT2h3Dv9WlL1woKMHVcCM+jFgYf/zgdKOOpdXMadGiMMUtIYlDdjghv1]
  - key: DATABASE_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${dbaas-db-3754887.HOSTNAME}
  - key: DATABASE_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${dbaas-db-3754887.PORT}
  - key: DATABASE_USER
    scope: RUN_AND_BUILD_TIME
    value: ${dbaas-db-3754887.USERNAME}
  - key: DATABASE_PW
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:YcMssXQshwC03XuUZKrPvNs3p9U6CMvv:2rAWPmkCXDkRf5RCTRh47x3ihj9XImFoY0a11ROfnEuT61BvjY0TUCwLdhQ=]
  - key: DATABASE_CERT
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:yDfCzbaaNsshQzPgB/wmkVl0ukATwNCG:PEJc6vCvmaNapX0J/n0oU1wSxRjOzJAzDzlGblEGmpG+7D6Ie5e5x0+A5A==]
  - key: DATABASE
    scope: RUN_AND_BUILD_TIME
    value: ${dbaas-db-3754887.DATABASE}
  - key: PRIVATE
    scope: RUN_AND_BUILD_TIME
    value: ${_self.PRIVATE_URL}
  - key: PUBLIC
    scope: RUN_AND_BUILD_TIME
    value: ${_self.PUBLIC_URL}
  - key: APP_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  github:
    branch: main
    deploy_on_push: true
    repo: LueYangYue/SIPP
  http_port: 8080
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: sipp
  run_command: heroku-php-apache2
  source_dir: /
- environment_slug: php
  github:
    branch: main
    deploy_on_push: true
    repo: LueYangYue/SIPP
  http_port: 8080
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: sipp-sipp-app
  run_command: heroku-php-apache2 public/
  source_dir: sipp-app
